# Generated by Django 4.2.1 on 2024-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_blogpage_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="trending",
            field=models.BooleanField(default=False),
        ),
    ]
